# -*- coding: utf-8 -*-
"""opencv_cannyedge.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_sfYp1ptZzoa1CBby2Rny0XhuEUeBDf-
"""

import numpy as np
import cv2 as cv

from matplotlib import pyplot as plt
img = cv.imread('/content/sample_data/messi.jpg', cv.IMREAD_GRAYSCALE)
assert img is not None, "File could not be read, check with os.path.exists()"
edges = cv.Canny(img,100,200)
plt.subplot(121),plt.imshow(img,cmap = 'gray')
plt.title('Original Image'), plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(edges,cmap = 'gray')
plt.title('Edge Image'), plt.xticks([]), plt.yticks([])

plt.show()